### ISSUE TITLE
Arduino controlled car randomly working

### ISSUE THREAD

**Issue by JasmaB** [Thought-Controlled-Machine/TCM-REP#1]
//Steps compiled by Rajesh Ramachandra and tested by Rajesh Ramachandra and Jasma Balasangameshwara

Issue details:
The car randomly responds to its remote or when powered through Arduino. 

The procedure followed for setting up Arduino Controlled Toy Car are as follows: 

Step 1 : Materials required
               1a.  Arduino UNO
               1b.  Male/Male Jumper Wires (4nos – 10cm each)
               1c.  AWG solid wire (4nos – 10 cm each)
               1d.  Rubber bands (2nos)
               1e.  9V battery with connector cable to power Arduino
               1f.     Remote toy car

Step 2 : Identify the trigger pins for Forward/Reverse and Left/Right on the chip inside the toy car.
             The pins identified on the toy car Rx chip are
             2a. 06 = Right Command
             2b. 07 = Left Command
             2c. 10 = Reverse Command
             2d. 11 = Forward Command

Step 3 : Solder the wires on the identified trigger pins. Male-to-Male wires were used for soldering.  

Step 4 : Prepare Arduino
            4a. Connect Arduino to a laptop using USB type A/B cable.
            4b. Configure the toy car's pins to Arduino pins as 
                             forward = 12, reverse = 11, left = 10, right = 9  //Refer ArduinoControlledCar.ino
            4c. Upload the ArduinoControlledCar.ino code to Arduino using Arduino IDE.
            4d. Connect jumper wires to pins 12,11,10,9 on Arduino
            4e. Connect 9V battery to the Arduino

Step 5 : Connect Arduino and Car
         5a. Connect the soldered cables on car to jumper wires on Arduino as per the PIN configuration:
             Behavior   'Pins on Car'   'Pins on Arduino'
             Forward            11                    12
             Reverse            10                    11
             Left                    7                    10
             Right                   6                     9

Step 6. Mount Arduino along with 9V battery on the car using rubber bands

Step 7: Fasten your seatbelts Power on the remote car. The car will move/turn as per the sequence mentioned in the code.

References
1.  http://www.instructables.com/id/Autonomous-Control-of-RC-Car-Using-Arduino/?

ALLSTEPS
2.  http://www.rcgroups.com/forums/showthread.php?t=675500
3.  https://www.arduino.cc/en/Tutorial/HomePage

**Comment by apk2134** [comment]
The Jumper wires connecting the toy car with arduino had loose connection.The connection has now been fixed.
